"""
Django settings for totalcb project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import sys

from totalcb import paths

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Compatibilidad con PyInstaller: cuando el proyecto se empaqueta como .exe,
# los activos de solo lectura (plantillas, estáticos) viven bajo
# ``sys._MEIPASS``; en desarrollo seguimos usando la raíz del repositorio.
if getattr(sys, "frozen", False) and hasattr(sys, "_MEIPASS"):
    BASE_DIR = Path(sys._MEIPASS)
else:
    BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bzuvrpzd1(genf&4s^5le1+z_33$x)v!8@p*dwsp6%s9^2nwae'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'conciliacion',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Sirve los estáticos en producción/empaquetado: Waitress no sirve estáticos,
    # así que WhiteNoise los entrega a través del WSGI application desde STATIC_ROOT.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'totalcb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates', paths.app_root() / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'totalcb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': paths.database_path(),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# --- Localización numérica regional (España/Paraguay) -----------------------
# Formato requerido para la UI financiera:
#   * Separador de millares: "."  →  1.500,50
#   * Separador decimal:     ","  →  1.500,50
#   * Agrupación de 3 dígitos.
#
# ``USE_L10N`` fue eliminado en Django 5.0: cuando ``USE_I18N = True`` la
# localización de formato está siempre activa, por lo que no es necesario
# declararlo.
USE_THOUSAND_SEPARATOR = True
NUMBER_GROUPING = 3
DECIMAL_SEPARATOR = ','
THOUSAND_SEPARATOR = '.'

# El módulo de formato ``es`` de Django usa un espacio de no separación como
# separador de millares en lugar de ".". Para garantizar el separador regional
# exacto se registra un módulo de formato propio, con prioridad sobre el de la
# distribución (las claves no definidas siguen resolviéndose por el estándar).
FORMAT_MODULE_PATH = ['totalcb.formats']


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

# Additional locations of static files (pre-compiled Tailwind + Alpine.js).
# ``BASE_DIR`` ya resuelve a ``sys._MEIPASS`` cuando el proyecto está congelado
# (PyInstaller), por lo que ``BASE_DIR / 'static'`` apunta a los activos
# desempaquetados en el .exe y a la raíz del repositorio en desarrollo.
STATICFILES_DIRS = [BASE_DIR / 'static']

# Where ``collectstatic`` gathers files for the frozen desktop build.
STATIC_ROOT = BASE_DIR / 'staticfiles'
