# Generated by Django 6.0.7 on 2026-09-05 17:48

import conciliacion.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'banco',
                'verbose_name_plural': 'bancos',
            },
        ),
        migrations.CreateModel(
            name='ConceptoAjuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'concepto de ajuste',
                'verbose_name_plural': 'conceptos de ajuste',
            },
        ),
        migrations.CreateModel(
            name='Conciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('draft', 'Borrador'), ('committed', 'Comprometida'), ('reverted', 'Revertida')], default='draft', max_length=20)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
            ],
            options={
                'verbose_name': 'conciliación',
                'verbose_name_plural': 'conciliaciones',
            },
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'tipo de cuenta',
                'verbose_name_plural': 'tipos de cuenta',
            },
        ),
        migrations.CreateModel(
            name='TipoOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'tipo de operación',
                'verbose_name_plural': 'tipos de operación',
            },
        ),
        migrations.CreateModel(
            name='AjusteConciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', conciliacion.models.ImporteDecimalField(decimal_places=8, max_digits=19)),
                ('concepto_ajuste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conciliacion.conceptoajuste')),
                ('conciliacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conciliacion.conciliacion')),
            ],
            options={
                'verbose_name': 'ajuste de conciliación',
                'verbose_name_plural': 'ajustes de conciliación',
            },
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=200)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conciliacion.banco')),
            ],
            options={
                'verbose_name': 'cuenta bancaria',
                'verbose_name_plural': 'cuentas bancarias',
            },
        ),
        migrations.AddField(
            model_name='conciliacion',
            name='cuenta_bancaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conciliacion.cuentabancaria'),
        ),
        migrations.CreateModel(
            name='LoteImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(max_length=255)),
                ('fecha_importacion', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'lote de importación',
                'verbose_name_plural': 'lotes de importación',
                'constraints': [models.UniqueConstraint(fields=('fuente', 'fecha_importacion'), name='lote_importacion_identidad_unica')],
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('cantidad_decimales', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'moneda',
                'verbose_name_plural': 'monedas',
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad_decimales__gte', 0)), name='moneda_cantidad_decimales_no_negativa')],
            },
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conciliacion.moneda'),
        ),
        migrations.CreateModel(
            name='MovimientoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', conciliacion.models.ImporteDecimalField(decimal_places=8, max_digits=19)),
                ('fecha', models.DateField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('en_consulta', models.BooleanField(default=False)),
                ('cuenta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conciliacion.cuentabancaria')),
                ('lote_importacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conciliacion.loteimportacion')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conciliacion.moneda')),
                ('tipo_operacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conciliacion.tipooperacion')),
            ],
            options={
                'verbose_name': 'movimiento bancario',
                'verbose_name_plural': 'movimientos bancarios',
            },
        ),
        migrations.CreateModel(
            name='DetalleConciliacionBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conciliacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conciliacion.conciliacion')),
                ('movimiento_bancario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conciliacion.movimientobancario')),
            ],
            options={
                'verbose_name': 'detalle de conciliación bancaria',
                'verbose_name_plural': 'detalles de conciliación bancaria',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', conciliacion.models.ImporteDecimalField(decimal_places=8, max_digits=19)),
                ('fecha', models.DateField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('lote_importacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conciliacion.loteimportacion')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conciliacion.moneda')),
                ('tipo_operacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conciliacion.tipooperacion')),
            ],
            options={
                'verbose_name': 'movimiento interno',
                'verbose_name_plural': 'movimientos internos',
            },
        ),
        migrations.CreateModel(
            name='DetalleConciliacionInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conciliacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conciliacion.conciliacion')),
                ('movimiento_interno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conciliacion.movimientointerno')),
            ],
            options={
                'verbose_name': 'detalle de conciliación interna',
                'verbose_name_plural': 'detalles de conciliación interna',
            },
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='tipo_cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conciliacion.tipocuenta'),
        ),
        migrations.AddConstraint(
            model_name='conciliacion',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['draft', 'committed', 'reverted'])), name='conciliacion_estado_valido'),
        ),
        migrations.AddConstraint(
            model_name='detalleconciliacionbancaria',
            constraint=models.UniqueConstraint(fields=('conciliacion', 'movimiento_bancario'), name='detalle_conciliacion_bancaria_unico'),
        ),
        migrations.AddConstraint(
            model_name='detalleconciliacioninterna',
            constraint=models.UniqueConstraint(fields=('conciliacion', 'movimiento_interno'), name='detalle_conciliacion_interna_unico'),
        ),
        migrations.AddConstraint(
            model_name='movimientointerno',
            constraint=models.CheckConstraint(condition=models.Q(('importe__gte', 0)), name='movimiento_interno_importe_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='movimientobancario',
            constraint=models.CheckConstraint(condition=models.Q(('importe__gte', 0)), name='movimiento_bancario_importe_no_negativo'),
        ),
    ]
