# Generated by Django 6.1.1 on 2026-09-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciliacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='conceptoajuste',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tipocuenta',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tipooperacion',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
