# Generated by Django 6.0.7 on 2026-09-09 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciliacion', '0003_cuentabancaria_redefinicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoLibro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('detalle', models.CharField(max_length=255)),
                ('debe', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('haber', models.DecimalField(decimal_places=2, default=0.0, max_digits=18)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=18)),
                ('conciliado', models.BooleanField(default=False)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conciliacion.cuentabancaria')),
                ('tipo_operacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conciliacion.tipooperacion')),
            ],
            options={
                'verbose_name': 'movimiento de libro',
                'verbose_name_plural': 'movimientos de libro',
                'ordering': ['fecha', 'id'],
            },
        ),
    ]
