# Generated by Django 6.0.7 on 2026-09-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciliacion', '0004_movimientolibro'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='movimientolibro',
            constraint=models.CheckConstraint(condition=models.Q(('debe__gte', 0)), name='movimiento_libro_debe_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='movimientolibro',
            constraint=models.CheckConstraint(condition=models.Q(('haber__gte', 0)), name='movimiento_libro_haber_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='movimientolibro',
            constraint=models.CheckConstraint(condition=models.Q(('debe__gt', 0), ('haber__gt', 0), _connector='OR'), name='movimiento_libro_importe_requerido'),
        ),
    ]
