# Generated by Django 6.1.1 on 2026-09-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciliacion', '0006_cuentabancaria_catalogos_protect'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='movimientolibro',
            constraint=models.CheckConstraint(condition=models.Q(('debe', 0), ('haber', 0), _connector='OR'), name='movimiento_libro_mutua_exclusion'),
        ),
    ]
