# Generated by Django 6.1.1 on 2026-09-18 14:12

import conciliacion.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciliacion', '0007_movimientolibro_movimiento_libro_mutua_exclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoExtracto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('detalle', models.CharField(max_length=255)),
                ('importe', conciliacion.models.ImporteDecimalField(decimal_places=2, max_digits=18)),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('importacion', 'Importación')], default='manual', max_length=20)),
                ('conciliado', models.BooleanField(default=False)),
                ('cuenta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_extracto', to='conciliacion.cuentabancaria')),
            ],
            options={
                'verbose_name': 'movimiento de extracto',
                'verbose_name_plural': 'movimientos de extracto',
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaPunteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(choices=[('puntear', 'Puntear'), ('despuntear', 'Despuntear')], max_length=20)),
                ('usuario', models.CharField(blank=True, max_length=150)),
                ('movimiento_libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conciliacion.movimientolibro')),
                ('movimiento_extracto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conciliacion.movimientoextracto')),
            ],
            options={
                'verbose_name': 'auditoría de punteo',
                'verbose_name_plural': 'auditorías de punteo',
            },
        ),
        migrations.CreateModel(
            name='Punteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimiento_extracto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='punteo', to='conciliacion.movimientoextracto')),
                ('movimiento_libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='punteo', to='conciliacion.movimientolibro')),
            ],
            options={
                'verbose_name': 'punteo',
                'verbose_name_plural': 'punteos',
            },
        ),
        migrations.AddConstraint(
            model_name='movimientoextracto',
            constraint=models.CheckConstraint(condition=models.Q(('importe__lt', 0), ('importe__gt', 0), _connector='OR'), name='movimiento_extracto_importe_no_cero'),
        ),
        migrations.AddConstraint(
            model_name='movimientoextracto',
            constraint=models.CheckConstraint(condition=models.Q(('origen__in', ['manual', 'importacion'])), name='movimiento_extracto_origen_valido'),
        ),
        migrations.AddConstraint(
            model_name='auditoriapunteo',
            constraint=models.CheckConstraint(condition=models.Q(('accion__in', ['puntear', 'despuntear'])), name='auditoria_punteo_accion_valida'),
        ),
        migrations.AddConstraint(
            model_name='punteo',
            constraint=models.UniqueConstraint(fields=('movimiento_extracto',), name='punteo_movimiento_extracto_unico'),
        ),
        migrations.AddConstraint(
            model_name='punteo',
            constraint=models.UniqueConstraint(fields=('movimiento_libro',), name='punteo_movimiento_libro_unico'),
        ),
    ]
