# Generated by Django 6.1.1 on 2026-09-19 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciliacion', '0008_movimientoextracto_punteo_auditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriapunteo',
            name='movimiento_extracto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conciliacion.movimientoextracto'),
        ),
        migrations.AlterField(
            model_name='auditoriapunteo',
            name='movimiento_libro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conciliacion.movimientolibro'),
        ),
    ]
